#! /bin/bash

function json2path ()
{

	declare {JSON,PRE,NAM,VAL,PST,RGX_{STRING{,_EDQ},NUMBER,WORD}}=

	RGX_STRING_EDQ="\"+([^\"]*[\\][\"][^\"]*)\""
	RGX_STRING="\"([^\"]*)\""
	RGX_NUMBER="([0-9\.\-\+eE]+)"
	RGX_WORD="(true|false|null)"
	RGX_OBJARY="(\[|{)"
	RGX_JSON_NXT="([^\"]*)(.*)"

	[ -n "${1}" ] \
		&& JSON="${1}" \
		|| JSON="$( cat - )"

	JSON="$( echo "${JSON}" | sed "s/^[[:blank:]]*//;s/[[:blank:]]*\$//" | tr -d "\n\r" | sed "s/\(\"[^\"\\]*\":\)[[:blank:]]/\1/g" )"

	while [ -n "${JSON}" ]
	do
		[[ "${JSON}" =~ ^([^\"]*)\"([^\"]*)\":(.*) ]]
		PRE="${BASH_REMATCH[1]}"
		NAM="${BASH_REMATCH[2]}"
		TMP="${BASH_REMATCH[3]}"
		[[ "${TMP}" =~ ^${RGX_STRING_EDQ}${RGX_JSON_NXT} ]] || \
		[[ "${TMP}" =~ ^${RGX_STRING}${RGX_JSON_NXT} ]] || \
		[[ "${TMP}" =~ ^${RGX_WORD}${RGX_JSON_NXT} ]] || \
		[[ "${TMP}" =~ ^${RGX_NUMBER}${RGX_JSON_NXT} ]] || \
		[[ "${TMP}" =~ ^${RGX_OBJARY}${RGX_JSON_NXT} ]]
		VAL="${BASH_REMATCH[1]}"
		PST="${BASH_REMATCH[2]}"
		JSON="${BASH_REMATCH[3]}"
		printf "\n%s\t%s\t%s\t%s\t%s\n" "${PRE}" "${NAM}" "${VAL}" "${PST}" "${JSON}"
	done
}

json2path "${@}"
